### ISSUE TITLE
Make CLI  accept a glob instead of hardcoding it

### ISSUE THREAD

**Issue by mathiasbynens** [billinghamj/fix-es-imports#2]
Let folks run:

```sh
npx fix-es-imports *.mjs
```

...instead of hardcoding the glob: https://github.com/billinghamj/fix-es-imports/blob/a55559cd05cce8b7642bcb30df70601d4dd90d21/cmd/index.js#L10

You could then even consider dropping the `glob` dependency.

**Comment by billinghamj** [comment]
Ah yeah, very fair point. Would be able to make a PR with this change?
